VERSION="2.2.1"

ACCOUNTS=[
"GBP5HMPKRZPAELNZG63ZNEGZZXTXUT6AMCRSX3TMKVIMT4E7ICR2W7UB",
]

[DOCUMENTATION]
ORG_NAME="Telosa"
ORG_URL="https://www.telosa-stellar.com/"
ORG_DESCRIPTION="Telosa is a proposed utopian planned US city conceived by American billionaire Marc Lore and announced in September 2021. The project has a target population of 5 million people by 2050, with the first phase of construction expected to house 50,000."
ORG_LOGO="https://www.telosa-stellar.com/tls.png"


[[CURRENCIES]]
code="Telosa"
status="live"
display_decimals=2
issuer="GBP5HMPKRZPAELNZG63ZNEGZZXTXUT6AMCRSX3TMKVIMT4E7ICR2W7UB"
anchor_asset_type="crypto"
name="Telosa City"
desc="Telosa is a proposed utopian planned US city conceived by American billionaire Marc Lore and announced in September 2021."
image="https://www.telosa-stellar.com/tls.png"
